version: '3.8'
services: 
  backend:
    container_name: backend
    build:
      context: backend
      dockerfile: Dockerfile # Dockerfile in server folder
    ports:
      - 5000:5000
    restart: always

  frontend:
    container_name: frontend
    build:
      context: frontend
      dockerfile: Dockerfile # Dockerfile in client folder
    ports:
      - 5173:5173
    restart: always